### ISSUE TITLE
Enable PRO Elements

### ISSUE THREAD

**Issue by zafai** [JoseSoteloCohen/sendy-elements#8]
Really cool Plugin for Elementor, we are running PRO Elements same as Elementor PRO but without support from Elementor.

https://proelements.org/

Would be great if sendy-elements also allow to run this and not only Elementor PRO

**Comment by JoseSoteloCohen** [comment]
Hello @zafai 

Thank you very much for doing this and taking the time to create a pull request, but sadly, I can't approve it because then I would need to keep up with the updates made on both plugins.

That being said, you can use the sendy elements code and create you own plugin that works for Pro Elements or both, but that's something that I'm not willing to do as I suspect that it will increase the amount of support tickets.

Wish you the best!

**Comment by zafai** [comment]
Hey @JoseSoteloCohen 

thank you for the reply and the explanation, Pro Elements is the codebase from Elementor Pro only the https://github.com/proelements/proelements/blob/master/pro-elements.php for the plugin is different to solve the naming issue.

Would be really nice if we could get this into your plugin to not maintaine two plugins with almost the same feature set.
